# Generated by Django 4.0.3 on 2022-06-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appw7dni', '0002_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
