# Generated by Django 4.0.3 on 2022-06-16 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appw7dni', '0003_remove_product_tags_delete_order_delete_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_shift', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_of_shift', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appw7dni.employee')),
            ],
        ),
    ]
