# Generated by Django 4.0.3 on 2022-06-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appw7dni', '0004_hourtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourtable',
            name='day_of_shift',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourtable',
            name='end_of_shift',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourtable',
            name='start_of_shift',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
