# Generated by Django 4.0.3 on 2022-06-18 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appw7dni', '0007_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourTableEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_shift', models.DateField(null=True)),
                ('end_of_shift', models.TimeField(null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appw7dni.employee')),
            ],
        ),
        migrations.CreateModel(
            name='HourTableStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_shift', models.DateField(null=True)),
                ('start_of_shift', models.TimeField(null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appw7dni.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='HourTable',
        ),
    ]
