# Generated by Django 4.0.3 on 2022-06-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appw7dni', '0008_hourtableend_hourtablestart_delete_hourtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourtableend',
            name='day_of_shift',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourtableend',
            name='end_of_shift',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourtablestart',
            name='day_of_shift',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourtablestart',
            name='start_of_shift',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
