# Generated by Django 4.0.3 on 2022-06-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appw7dni', '0010_alter_hourtableend_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourtableend',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appw7dni.employee'),
        ),
    ]
