# Generated by Django 4.0.3 on 2022-06-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appw7dni', '0012_alter_hourtableend_day_of_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourtableend',
            name='day_of_shift',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourtablestart',
            name='day_of_shift',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
