# Generated by Django 4.0.3 on 2022-06-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appw7dni', '0013_alter_hourtableend_day_of_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourtableend',
            name='building',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hourtablestart',
            name='building',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
