# Generated by Django 4.0.3 on 2022-06-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appw7dni', '0016_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
    ]
