# Generated by Django 4.0.3 on 2022-06-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appw7dni', '0017_remove_employee_email_remove_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
